spring:
  #dubbo 配置
  dubbo:
    application:
      name: course-service
    registry:
      address: zookeeper://${zookeeper.address}:2181
    protocol:
      name: dubbo
      port: 20880
      #host: 127.0.0.1
    scan: n.kidding.course

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.address}:3306/db_course
    username: root
    password: 123456

thrift:
  user:
    ip: user-service
    port: 7911
